### ISSUE TITLE
Browser fails to download

### ISSUE THREAD

**Issue by ghost** [bgempire/bgarmor#1]
Hi,

The bgarmor-v0.0.5-win-linux.zip download fails.
Browser reports virus.

**Comment by joelgomes1994** [comment]
Thanks for reporting! I got some reports about this issue before... This is due to antivirus programs tendency to detect some malicious patterns in executables. In the case of BGArmor, probably it detects a shell execution logic (specifically [here](https://github.com/bgempire/bgarmor/blob/master/source/Launcher.c#L184)) and just assumes it as malicious.
I started working on a new launcher written in Rust insted of C in [this branch](https://github.com/bgempire/bgarmor/tree/rust-launcher), so I hope this issue gets fixed when it's done.
